apiVersion: v1
kind: Secret
metadata:
    name: mysecret
    namespace: demoapp
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:VryUuplEKw==,iv:0mhYARlOIvcV7qqUc3/ffToI7pdp14QJ2OJazRqEe1A=,tag:ItS+8j8weV6iICTd2VGsrw==,type:str]
    password: ENC[AES256_GCM,data:9z4QeIG/tu5QyTDbkKLOD5A=,iv:zv9XwJPwGQ9Q007j8BLkawv6rgCOqqK1bibg/+N4vC8=,tag:GUb6qTzSbOYj51RWbxomIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://gitopsdemokeyvault.vault.azure.net
          name: sops-key
          version: b7bc85c1a4ef4180be9d1de46725304c
          created_at: "2021-05-10T13:31:01Z"
          enc: UVdu_UWSdPstrTIWDXCg3D-AuIzHKxSw3lb158ozeRwWI-IiTbzcFnHIpH2uVD0jTE3FzcDGerifD0dm1aodN2k7gpZ6Wt7lhQpdYvG3qYHLjKBOS7x8tfWoFgzMQJOH5n8E4bF_UvBmh_V4CYXpWfe5RX92zqLHgu9kzpem33u3LH9gIlosj7nzHZBL3kvgpIduVqRvBQMGXGJMqxjTjyu9Thn3eye-fk0XYkioKMIoOjCJTP7NebOzFNHA5n2BgeA-PScIrLb_CU7k36JUW9yAXFW8hVTePCZhWMnQa7HrEBH4zMhCnKAgFfUBFNW_nlybcfk0AexF_l12NrmWVg
        - vault_url: https://gitopsdemokeyvault.vault.azure.net
          name: sops-key
          version: 2862a8c9f09c4ba49254dc3764b5f8bf
          created_at: "2021-05-13T10:26:07Z"
          enc: ZMkmlAncdMens1gjUm-55uwDJQRxjgY7PK7UjYfqy3k7knlShvemIaJ8icMvr17ff5TLX8Eb_KjUSS_JXaFxeyv9a_ze00qcsTl5dKUSUsdLwIzGKp7KKnaTe3pPCn6E_rZcFrAQfimiWqbyikitiN9R0oQpUOsIhsDPhV6mGtxyz3J3kUGLKkI4k47u8mTq-SP7517kNpG9k42LsBF9tI5fvuq246TM20oXHYp5qEksse7nzK6k-uhXfVn_HJH2FYt_KYYG9vBIzPBbP_ZvSOoiLdScq8uFCM2jyuOFNACli7shDPZJCcaHpW7kj9HAEpWSu8KcP8-yS7q62vE0oA
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T10:26:11Z"
    mac: ENC[AES256_GCM,data:aZbiwJZZsZuuzN5YoKfposu0zTjVI+b3JPkPCwkVeVISQ1Ppd0yQLWQ8HPbwmc8yE/d2Uojst2C88LMurrItUgOjyvG6F/AKPHG3Zx700ga768JzG4v1dIv7e6g6IgatMroRn/ossKIzijdMhBlx7aWpQX+EJe/DB53wCfROi+w=,iv:fqb6cWFsxucX4C7AIajY3pHrNedVMdgDeIphlmyuS2E=,tag:nbpj54e4eqa3idVreLMArw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
