apiVersion: v1
kind: Secret
metadata:
    name: mysecret
    namespace: demoapp
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:WNLjKXAwMw==,iv:0mhYARlOIvcV7qqUc3/ffToI7pdp14QJ2OJazRqEe1A=,tag:V0BoL03j2f9oVHXftv0kUg==,type:str]
    password: ENC[AES256_GCM,data:7hpoWNhrh23j4vsXwfQcKis=,iv:zv9XwJPwGQ9Q007j8BLkawv6rgCOqqK1bibg/+N4vC8=,tag:m9gr0m7FdL+RXR+1Wht8Pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://gitopsdemokeyvault.vault.azure.net
          name: sops-key
          version: 2862a8c9f09c4ba49254dc3764b5f8bf
          created_at: "2021-05-13T10:26:07Z"
          enc: Zr5myUPi2nH7gjSSwsFSpv97MGdztQS9nFLHY60BeN3MRf260aZbQVt6afxOGa9DCfAuvD3cEpqTU8C6_UP8aJQOh5tiNGQCk2rCCpFzt2c2OdwipViNB3CpDAhzwMz_LgVXRCPFIJWG3TVkD-Odkav_dvwyMgcHBkssGfZZRQTK5tMjhf_l8oNZFuFyZZ-_Oi7hOdRbFdv4SwgZXHu01FUwehwrc2QFHz04vYmisoLKx2DhzKoVKl9yC0K4LeKLIJBtwpUzSA-MfZP9CEm8jEFpBPCxRsKWg7H2bcDnPmrcd8g3O6wz-AT5uAZkKM_L0V75lDSuREwETqrHtNJYUg
    hc_vault: []
    age: []
    lastmodified: "2021-05-13T10:27:36Z"
    mac: ENC[AES256_GCM,data:cAum9ccnVIgMNZdPbb1ROV+i1pYEU/f8d/9/VFurllat0VW5HSFvvLFPaSUkDRp1ma36yJhur9Rlec27tyN8tzE4Lr8ir2eTV2/Wxih9hpZh7PZvmyi//51UAzBkruJ9DaGRb7GzC8jfa5rmIwJmIbFM2aAM9D67qNOO8ZjutgI=,iv:vEziBtN4stF+snDHeLBJjcGVEs7F7oqs3ezStuYEDgg=,tag:kmXzNwzYRfQUjWEVYCrxaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
