---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageUpdateAutomation
metadata:
  name: demoapp
  namespace: demoapp
spec:
  checkout:
    branch: main
    gitRepositoryRef:
      name: demoapp
  commit:
    authorEmail: fluxcdbot@users.noreply.github.com
    authorName: fluxcdbot
    messageTemplate: "{{range .Updated.Images}}{{println .}}{{end}}"
  interval: 1m0s
  push:
    branch: main
  update:
    path: ./manifests
    strategy: Setters
