---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: demoapp
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: demoapp
  policy:
    semver:
      range: ">=1.0.0"
