---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: demoapp
  namespace: demoapp
spec:
  imageRepositoryRef:
    name: demoapp
  policy:
    semver:
      range: ">=1.0.0"
